import { ArrowRight, BarChart3, ClipboardPenLine } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { FormCard } from "../components/FormCard";
import { FORMS, getForm } from "../forms";
import { formatTimestamp } from "../lib/format";
import { hasDeviceToken } from "../lib/device";
import { listLocalEntries, type LocalEntry } from "../lib/offlineDb";
const order=[3,9,4,7,2,1,8];
function draftLabel(entry:LocalEntry){const context=entry.context;return [context.date,context.shift,context.timeSlot,context.boilerNumber?`Boiler ${context.boilerNumber}`:null].filter(Boolean).join(" · ");}
export function HomePage(){const navigate=useNavigate();const[dataForm,setDataForm]=useState(FORMS[0].key);const[drafts,setDrafts]=useState<LocalEntry[]>([]);const canCreate=hasDeviceToken();const manual=order.flatMap(n=>{const f=FORMS.find(x=>x.number===n);return f?[f]:[]});const f5=getForm("daily-consumption-totals")!;const f6=getForm("makeup")!;
  useEffect(()=>{const load=()=>void listLocalEntries().then(entries=>setDrafts(entries.filter(entry=>entry.status==="draft").slice(0,12)));void load();window.addEventListener("ecc-local-change",load);return()=>window.removeEventListener("ecc-local-change",load);},[]);
  return <div className="page-stack"><section><div className="section-heading-row compact"><div><div className="section-icon"><ClipboardPenLine size={21}/></div><h2>Form Entry</h2><p>Select the operator check you are completing. Form 5 and Form 6 are read-only local-first projections with server fallback.</p></div></div><div className="form-card-grid">{manual.map(form=><FormCard key={form.key} form={form} showNewEntry={canCreate} child={form.number===8?<div style={{display:"grid",gap:8,marginTop:16}}><Link to={`/forms/${f5.key}`} className="derived-child"><div><span>Form 5 · Local-first projection</span><strong>{f5.name}</strong></div><ArrowRight size={17}/></Link><Link to={`/forms/${f6.key}`} className="derived-child"><div><span>Form 6 · Local-first projection</span><strong>{f6.name}</strong></div><ArrowRight size={17}/></Link></div>:undefined}/>)}</div></section>{drafts.length>0&&<section className="card-surface"><div className="entries-title"><div><h2>Resume local drafts</h2><p>{drafts.length} draft{drafts.length===1?"":"s"} saved on this tablet</p></div></div><div className="draft-choice-list">{drafts.map(entry=><Link className="draft-choice" key={entry.entryId} to={`/forms/${entry.formKey}/record/${encodeURIComponent(entry.entryId)}`}><strong>{getForm(entry.formKey)?.number}. {getForm(entry.formKey)?.name}</strong><span>{draftLabel(entry)} · saved {formatTimestamp(entry.updatedAt)}</span></Link>)}</div></section>}<section className="data-entry-panel"><div className="section-heading-row compact"><div><div className="section-icon"><BarChart3 size={21}/></div><h2>Data Viewing</h2><p>{canCreate?"View local drafts and completed entries, with cloud refresh only when available.":"View completed records from Cloudflare in read-only mode."}</p></div></div><div className="data-view-picker"><label><span>Form</span><select value={dataForm} onChange={e=>setDataForm(e.target.value)}>{FORMS.map(f=><option key={f.key} value={f.key}>{f.number}. {f.name}</option>)}</select></label><button className="primary-button" onClick={()=>navigate(`/data/${dataForm}`)}>View entries <ArrowRight size={17}/></button></div></section></div>;}
