import { Cloud, Database, KeyRound, Play, Plus, RefreshCw, Save, Server, UserMinus, UserPlus } from "lucide-react";
import { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { createOperator, getBackupStatus, getMeta, listOperators, runBackup, updateOperator } from "../lib/api";
import { getDeviceToken, setDeviceToken } from "../lib/device";
import { formatTimestamp, todayPlantDate } from "../lib/format";
import { offlineDb, putOperators } from "../lib/offlineDb";
import { getSyncSnapshot, subscribeSync, syncNow } from "../lib/sync";
import type { OperatorRecord } from "../types";

export function SystemPage(){
  const sync=useSyncExternalStore(subscribeSync,getSyncSnapshot,getSyncSnapshot);const[token,setToken]=useState(getDeviceToken());const[meta,setMeta]=useState<any>(null);const[backupDate,setBackupDate]=useState(todayPlantDate());const[backups,setBackups]=useState<any[]>([]);const[operators,setOperators]=useState<OperatorRecord[]>([]);const[newOperator,setNewOperator]=useState("");const[counts,setCounts]=useState({entries:0,pendingUploads:0,cache:0});const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[polling,setPolling]=useState(false);
  async function refresh(){setBusy(true);try{const [m,b,o,e,p,cache]=await Promise.all([getMeta(),getBackupStatus(),listOperators(),offlineDb.entries.count(),offlineDb.completedSync.count(),offlineDb.serverCache.count()]);setMeta(m);setBackups(b.generations);setOperators(o.operators);await putOperators(o.operators);setCounts({entries:e,pendingUploads:p,cache});setMessage(null);}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  useEffect(()=>{void refresh();},[]);
  useEffect(()=>{if(!polling)return;const id=window.setInterval(async()=>{try{const b=await getBackupStatus();setBackups(b.generations);const active=b.generations.some((x:any)=>["ready","delivering","reconciling"].includes(x.status));if(!active)setPolling(false);}catch{/* keep current status */}},4000);return()=>clearInterval(id);},[polling]);
  async function startBackup(){setBusy(true);try{const r=await runBackup(backupDate);setMessage(`Backup workflow ${r.workflowInstanceId} accepted for ${backupDate}. D1 will show verified only after SharePoint echoes the exact generation ID and hash.`);setPolling(true);}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function addOperator(){const name=newOperator.trim();if(!name)return;setBusy(true);try{await createOperator(name);setNewOperator("");await refresh();}finally{setBusy(false);}}
  const latestByDate=useMemo(()=>{const m=new Map<string,any>();for(const row of backups)if(!m.has(row.plant_date))m.set(row.plant_date,row);return[...m.values()].slice(0,20);},[backups]);
  return <div className="page-stack"><div className="page-hero"><div><div className="eyebrow">Diagnostics and recovery</div><h1>System</h1><p>This tablet's IndexedDB is authoritative for local drafts and completions. Cloud upload and nightly SharePoint backup are background copies.</p></div><button className="secondary-button" onClick={()=>void refresh()} disabled={busy}><RefreshCw className={busy?"spin":""} size={17}/> Refresh</button></div>{message&&<div className="notice"><Cloud size={18}/>{message}</div>}
  <div className="system-grid"><section className="card-surface system-card"><div className="section-heading-row compact"><div><div className="section-icon"><KeyRound size={19}/></div><h2>Tablet authorization</h2><p>The device token is stored only on this tablet and sent as a request header.</p></div></div><label className="metadata-field"><span>Device token</span><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste DEVICE_TOKEN"/></label><div className="confirmation-actions"><button className="primary-button" onClick={()=>{setDeviceToken(token);setMessage("Device token saved on this tablet.");void refresh();}}><Save size={16}/> Save token</button></div></section>
  <section className="card-surface system-card"><div className="section-heading-row compact"><div><div className="section-icon"><Server size={19}/></div><h2>Protocol / sync</h2><p>Incompatible clients are blocked from writes.</p></div></div><div className="status-list"><div><span>Connection</span><strong>{sync.online?"Online":"Offline"}</strong></div><div><span>Compatibility</span><strong>{sync.compatibility}</strong></div><div><span>Pending commands</span><strong>{sync.pending}</strong></div><div><span>Protocol</span><strong>{meta?.protocolVersion??"—"}</strong></div><div><span>Schema</span><strong>{meta?.schemaVersion??"—"}</strong></div></div><button className="secondary-button inline" onClick={()=>void syncNow()}><RefreshCw size={16}/> Sync now</button></section>
  <section className="card-surface system-card"><div className="section-heading-row compact"><div><div className="section-icon"><Database size={19}/></div><h2>Local durable store</h2><p>IndexedDB is authoritative for local drafts and completed forms. Only completed snapshots enter the upload queue.</p></div></div><div className="status-list"><div><span>Local entries</span><strong>{counts.entries}</strong></div><div><span>Completed upload queue</span><strong>{counts.pendingUploads}</strong></div><div><span>Cached cloud records</span><strong>{counts.cache}</strong></div></div></section></div>
  <section className="card-surface"><div className="entries-title"><div><h2>Immutable SharePoint backup generations</h2><p>Retries reuse the same frozen canonical JSON bytes, generation ID, delivery ID, and SHA-256 hash.</p></div></div><div className="data-entry-panel" style={{border:0,boxShadow:"none"}}><div className="data-view-picker"><label><span>Plant date</span><input type="date" value={backupDate} onChange={e=>setBackupDate(e.target.value)}/></label><button className="primary-button" disabled={busy} onClick={()=>void startBackup()}><Play size={16}/> Run / reconcile backup</button></div></div><div style={{overflowX:"auto"}}><table className="records-table"><thead><tr><th>Date</th><th>Generation</th><th>Status</th><th>Attempts</th><th>Hash</th><th>Verified</th><th>Files</th></tr></thead><tbody>{latestByDate.map(row=><tr key={row.generation_id}><td>{row.plant_date}</td><td>G{String(row.generation_number).padStart(3,"0")}</td><td><span className="tag">{row.status}</span></td><td>{row.delivery_attempts??row.attempt_count}</td><td><code>{row.payload_hash?String(row.payload_hash).slice(0,12):"—"}</code></td><td>{formatTimestamp(row.verified_at)}</td><td><small>{row.json_file_name??""}<br/>{row.xlsx_file_name??""}</small></td></tr>)}</tbody></table></div>{latestByDate.length===0&&<div className="empty-state small">No backup generations yet.</div>}</section>
  <section className="card-surface"><div className="entries-title"><div><h2>Operators</h2><p>No login or PIN. The selected operator is written into each revision.</p></div></div><div className="operator-admin"><div className="data-view-picker"><label><span>New operator</span><input value={newOperator} onChange={e=>setNewOperator(e.target.value)} placeholder="Name"/></label><button className="primary-button" disabled={busy||!newOperator.trim()} onClick={()=>void addOperator()}><UserPlus size={16}/> Add</button></div>{operators.map(o=><div className="operator-admin-row" key={o.id}><span>{o.name}</span><span className="tag">{o.active?"Active":"Inactive"}</span><button className="secondary-button" onClick={async()=>{await updateOperator(o.id,{active:!o.active});await refresh();}}>{o.active?<><UserMinus size={16}/> Deactivate</>:<><Plus size={16}/> Reactivate</>}</button></div>)}</div></section></div>;
}
