import type { FieldDefinition, FormDefinition, SectionDefinition } from "./types";

const n = (
  key: string,
  label: string,
  options: Partial<FieldDefinition> = {},
): FieldDefinition => ({ key, label, type: "number", trendable: true, ...options });

const t = (
  key: string,
  label: string,
  options: Partial<FieldDefinition> = {},
): FieldDefinition => ({ key, label, type: "text", ...options });

const section = (key: string, title: string, fields: FieldDefinition[], description?: string): SectionDefinition => ({
  key,
  title,
  fields,
  description,
});

const range = (label: string, min?: number, max?: number) => ({ label, min, max });

export const FORMS: FormDefinition[] = [
  {
    key: "ecc-cooling-tower-water-control-tests",
    number: 1,
    version: 1,
    name: "ECC Cooling Tower Water Control Tests",
    backupWorksheetName: "01 Cooling Tower",
    schedule: "shift",
    hasShift: true,
    sections: [
      section("cooling-tower", "ECC Cooling Tower Water Control Tests", [
        n("ct_meter", "CT Meter"),
        n("conductivity", "Conductivity", { target: range("1100–1200", 1100, 1200) }),
        n("ph", "pH", { target: range("8.3–9.0", 8.3, 9.0) }),
        n("f_chlorine", "F-Chlorine", { target: range("0.5–1.0", 0.5, 1.0), optional: true, infrequent: true }),
        n("orp", "ORP", { helpText: "Target TBD" }),
        n("molybdenum", "Molybdenum", { unit: "ppm", target: range("0.8–1.25 ppm", 0.8, 1.25) }),
        t("pump_sp_st", "Pump Sp/St"),
      ]),
      section("chilled-water", "ECC Chilled Water", [
        n("chilled_conductivity", "Conductivity Record", { optional: true, infrequent: true }),
        n("chilled_ph", "pH", { target: range("8.5–10", 8.5, 10), optional: true, infrequent: true }),
        n("chilled_po4", "PO4", { unit: "ppm", target: range("8–15 ppm", 8, 15), optional: true, infrequent: true }),
        { key: "chilled_additions", label: "Additions — Pump Run Time", type: "duration", optional: true, infrequent: true, trendable: true },
      ]),
    ],
  },
  {
    key: "boiler-water-control-tests",
    number: 2,
    version: 2,
    name: "Boiler Water Control Tests",
    backupWorksheetName: "02 Boiler Water",
    schedule: "shift",
    hasShift: true,
    hasBoiler: true,
    sections: [
      section("chemistry", "Boiler Chemistry", [
        n("p_alk", "P-ALK", { target: range("350–600", 350, 600) }),
        n("m_alk", "M-ALK", { target: range("400–800", 400, 800) }),
        n("oh_alk", "OH-ALK", { target: range("200–600", 200, 600), calculated: true, helpText: "Calculated: (P-ALK × 2) - M-ALK" }),
        n("blr_cond", "BLR COND", { target: range("3700–4200", 3700, 4200) }),
        n("sulfite", "SULFITE", { target: range("30–60", 30, 60) }),
        n("blr_mo", "BLR MO", { target: range("0.75–1.5", 0.75, 1.5) }),
        n("ph", "pH", { target: range("10–11.5", 10, 11.5) }),
      ]),
      section("operating", "Operating / Chemical Data", [
        n("steam_total", "Steam Total", { optional: true, infrequent: true }),
        n("makeup_total", "Makeup Total", { optional: true, infrequent: true }),
        n("am", "AM", { unit: "L" }),
        n("so3", "SO3", { unit: "L" }),
        n("sc", "SC", { unit: "L" }),
        n("bd", "BD", { unit: "Turn" }),
      ]),
    ],
  },
  {
    key: "yst-yk-chiller",
    number: 3,
    version: 1,
    name: "YST/YK Chiller",
    backupWorksheetName: "03 YST-YK Chiller",
    schedule: "time-slot",
    hasTimeSlot: true,
    sections: [
      section("general", "General", [
        n("hour_meter", "Hour Meter Reading"),
        n("oat", "OAT"),
        { key: "drive", label: "Drive", type: "select", options: [{ label: "YST", value: "YST" }, { label: "YK", value: "YK" }] },
      ]),
      section("motor", "Motor", [
        n("motor_full_load_amps", "% Full Load Amps (YK)", { unit: "%" }),
        n("motor_input_power", "Input Power"),
        n("motor_output_voltage", "Output Voltage"),
        n("motor_vsd_frequency", "VSD Frequency", { unit: "Hz" }),
      ]),
      section("turbine", "Turbine", [
        n("turbine_steam_flow", "Steam Flow", { unit: "lbs/hr" }),
        n("turbine_governor_valve", "% Governor Valve (YST)", { unit: "%" }),
        n("turbine_speed", "Speed"),
        n("turbine_speed_setpoint", "Speed Setpoint"),
        n("turbine_exhaust_pressure", "Exhaust Pressure"),
        n("turbine_bearing_de", "Bearing Temperature (DE)"),
        n("turbine_bearing_nde", "Bearing Temperature (NDE)"),
      ]),
      section("condenser", "Condenser", [
        n("condenser_entering_temp", "Entering Temperature"),
        n("condenser_leaving_temp", "Leaving Temperature"),
        n("condenser_pressure", "Pressure"),
        n("condenser_saturation_temp", "Saturation Temperature"),
        n("condenser_flow_gpm", "Flow Rate", { unit: "GPM" }),
      ]),
      section("evaporator", "Evaporator", [
        n("evaporator_entering_temp", "Entering Temperature"),
        n("evaporator_leaving_temp", "Leaving Temperature"),
        n("evaporator_pressure", "Pressure"),
        n("evaporator_saturation_temp", "Saturation Temperature"),
        n("evaporator_flow_gpm", "Flow Rate", { unit: "GPM" }),
      ]),
      section("compressor", "Compressor", [
        n("compressor_oil_pressure", "Oil Pressure"),
        n("compressor_oil_sump_temp", "Oil Sump Temperature"),
        n("compressor_discharge_temp", "Discharge Temperature"),
        { key: "compressor_oil_level", label: "Oil Level", type: "select", options: [{ label: "OK", value: "OK" }, { label: "Low", value: "Low" }] },
        n("compressor_hgbp", "HGBP", { unit: "%" }),
        n("compressor_prv", "PRV", { unit: "%" }),
      ]),
    ],
  },
  {
    key: "york-centrifugal-chiller",
    number: 4,
    version: 1,
    name: "York Centrifugal Chiller",
    backupWorksheetName: "04 York Chiller",
    schedule: "time-slot",
    hasTimeSlot: true,
    description: "Entry order follows the operators' physical walk-through order.",
    sections: [
      section("readings", "Readings", [
        { key: "oat_db_wb", label: "1. Outside Air Temperature D.B./W.B.", type: "paired-number", pairedLabels: ["DB", "WB"], trendable: false },
        n("evap_chw_inlet_pressure", "2. Evaporator — Chilled Water — Inlet Pressure"),
        n("evap_chw_outlet_pressure", "3. Evaporator — Chilled Water — Outlet Pressure"),
        { key: "compressor_oil_level", label: "4. Compressor — Oil Level", type: "select", options: [{ label: "OK", value: "OK" }, { label: "Low", value: "Low" }] },
        n("motor_volts", "5. Compressor — Motor — Volts"),
        n("motor_amps", "6. Compressor — Motor — Amps"),
        n("cond_water_inlet_pressure", "7. Condenser — Water — Inlet Pressure"),
        n("cond_water_outlet_pressure", "8. Condenser — Water — Outlet Pressure"),
        n("evap_chw_inlet_temp", "9. Evaporator — Chilled Water — Inlet Temperature"),
        n("evap_chw_outlet_temp", "10. Evaporator — Chilled Water — Outlet Temperature"),
        n("evap_freon_suction_pressure", "11. Evaporator — Freon Suction Pressure"),
        n("cond_freon_discharge_pressure", "12. Condenser — Freon — Discharge Pressure"),
        n("compressor_oil_pressure", "13. Compressor — Oil Pressure"),
        n("cond_water_inlet_temp", "14. Condenser — Water — Inlet Temperature"),
        n("cond_water_outlet_temp", "15. Condenser — Water — Outlet Temperature"),
        n("motor_full_load_amps", "16. Compressor — Motor — % Full Load Amps", { unit: "%" }),
        n("hour_meter", "17. Hour Meter Reading"),
        n("compressor_suction_temp", "18. Compressor — Suction Temperature"),
        n("compressor_discharge_temp", "19. Compressor — Discharge Temperature"),
        n("compressor_oil_temp", "20. Compressor — Oil Temperature"),
        n("cond_freon_discharge_temp", "21. Condenser — Freon — Discharge Temperature"),
      ]),
    ],
  },
  {
    key: "daily-consumption-totals",
    number: 5,
    version: 2,
    name: "Daily Consumption Totals",
    backupWorksheetName: "05 Daily Consumption",
    schedule: "derived",
    derivedFrom: "integrator-readings",
    description: "Read-only local projection from the exact completed Form 8 records for this date and the previous calendar date.",
    sections: [
      section("weather", "Outside Air Temperature", [
        n("oat_high", "OAT High", { calculated: true }),
        n("oat_low", "OAT Low", { calculated: true }),
      ]),
      section("boiler-2", "Boiler 2", [
        n("boiler2_gas_used", "Gas Used", { calculated: true }),
        n("boiler2_steam_used", "Boiler Steam", { calculated: true }),
      ]),
      section("boiler-3", "Boiler 3", [
        n("boiler3_gas_used", "Gas Used", { calculated: true, optional: true }),
        n("boiler3_steam_used", "Boiler Steam", { calculated: true, optional: true }),
        n("boiler3_lbs_steam_per_cuft_gas", "LBS. STM per CU.FT. GAS", { calculated: true, optional: true }),
      ]),
      section("boiler-4", "Boiler 4", [
        n("boiler4_gas_used", "Gas Used", { calculated: true, optional: true }),
        n("boiler4_steam_used", "Boiler Steam", { calculated: true, optional: true }),
        n("boiler4_lbs_steam_per_cuft_gas", "LBS. STM per CU.FT. GAS", { calculated: true, optional: true }),
      ]),
      section("daily-totals", "Daily Totals", [
        n("total_steam", "Total Steam", { calculated: true }),
        n("average_flow_hr", "Average Flow/Hr.", { calculated: true }),
        n("makeup_water_gallon", "Make-Up Water — Gallon", { calculated: true }),
        n("makeup_percent", "%", { calculated: true, helpText: "Make-Up Water Gallon ÷ Total Steam × 1000" }),
      ]),
    ],
  },
  {
    key: "makeup",
    number: 6,
    version: 2,
    name: "Makeup",
    backupWorksheetName: "06 Makeup",
    schedule: "derived",
    derivedFrom: "integrator-readings",
    description: "Read-only local projection from the exact current and previous calendar-date Form 8 records.",
    sections: [
      section("readings", "Derived Makeup Readings", [
        n("cw_makeup_current", "C.W. Makeup — Current Reading", { calculated: true }),
        n("cw_makeup_used", "C.W. Makeup — Daily Usage", { calculated: true, helpText: "Current date C.W. Makeup minus previous calendar date C.W. Makeup" }),
        n("tower_makeup_current", "Tower Makeup — Current Reading", { calculated: true }),
      ]),
    ],
  },
  {
    key: "boiler-water-pretreatment-condensate-tests",
    number: 7,
    version: 1,
    name: "Boiler Water Pretreatment & Condensate Tests",
    backupWorksheetName: "07 Pretreatment",
    schedule: "shift",
    hasShift: true,
    sections: [
      section("softener", "Softener", [
        n("softener_th", "TH", { target: range("< 0.5", undefined, 0.5) }),
        n("softener_conductivity", "Conductivity", { optional: true, infrequent: true }),
      ]),
      section("feedwater", "Feedwater", [
        n("feedwater_th", "TH", { target: range("< 0.5", undefined, 0.5) }),
        n("feedwater_conductivity", "Conductivity"),
        n("feedwater_ph", "pH", { target: range("8.4–9.5", 8.4, 9.5) }),
      ]),
      section("condensate", "Condensate", [
        n("condensate_th", "TH", { target: range("< 0.2", undefined, 0.2) }),
        n("condensate_conductivity", "Conductivity", { target: range("10–50", 10, 50) }),
        n("condensate_ph", "pH", { target: range("8–9", 8, 9) }),
      ]),
    ],
  },
  {
    key: "integrator-readings",
    number: 8,
    version: 2,
    name: "Integrator Readings",
    backupWorksheetName: "08 Integrator",
    schedule: "daily",
    description: "Completing this form deterministically refreshes Forms 5 and 6 from the exact accepted revision.",
    sections: [
      section("weather", "Outside Air Temperature", [
        n("oat_high", "OAT High", { unit: "°F" }),
        n("oat_low", "OAT Low", { unit: "°F" }),
      ]),
      section("water-steam", "Water / Steam", [
        n("softener1", "Softener 1", { optional: true }),
        n("softener2", "Softener 2", { optional: true }),
        n("reverse_osmosis", "Reverse Osmosis", { optional: true }),
        n("steam_boiler2", "Steam — Boiler 2", { optional: true }),
        n("steam_boiler3", "Steam — Boiler 3", { optional: true }),
        n("steam_boiler4", "Steam — Boiler 4", { optional: true }),
        n("hotwell_makeup", "Hotwell Makeup", { optional: true }),
      ]),
      section("electric-gas", "Electrical / Gas", [
        n("generated_kwh", "Generated KWH", { optional: true }),
        n("utility_kwh", "Utility KWH", { defaultValue: 240000 }),
        n("dump_cond_steam", "Dump Cond. Steam", { optional: true }),
        n("gas_boiler2", "Gas — Boiler 2", { optional: true }),
        n("gas_boiler3", "Gas — Boiler 3", { optional: true }),
        n("gas_boiler4", "Gas — Boiler 4", { optional: true }),
        n("cw_makeup", "C.W. Makeup", { optional: true }),
        n("tower_makeup", "Tower Makeup", { optional: true }),
      ]),
    ],
  },
  {
    key: "gas-turbine-log-sheet",
    number: 9,
    version: 1,
    name: "GAS TURBINE LOG SHEET",
    backupWorksheetName: "09 Gas Turbine",
    schedule: "time-slot",
    hasTimeSlot: true,
    aiAssisted: true,
    description: "Take a guided photo of the DCS log screen, verify extracted readings, then fill the remaining manual fields.",
    sections: [
      section("oat-memorial", "O.A.T. Memorial", [
        n("oat_memorial", "O.A.T. Memorial", { optional: true }),
      ]),
      section("dcs-readings", "DCS / Main Log Readings", [
        n("generator_stator_phase_a", "Generator Stator Phase A", { unit: "°F", aiExtract: true }),
        n("generator_stator_phase_b", "Generator Stator Phase B", { unit: "°F", aiExtract: true }),
        n("generator_stator_phase_c", "Generator Stator Phase C", { unit: "°F", aiExtract: true }),
        n("generator_drive_end", "Generator Drive End", { unit: "°F", aiExtract: true }),
        n("generator_non_drive_end", "Generator Non-Drive End", { unit: "°F", aiExtract: true }),
        n("generator_forward_thrust", "Generator Forward Thrust", { unit: "°F", aiExtract: true }),
        n("generator_aft_thrust", "Generator Aft Thrust", { unit: "°F", aiExtract: true }),
        n("lube_reservoir", "Lube Reservoir", { unit: "°F", aiExtract: true }),
        n("lube_supply", "Lube Supply", { unit: "°F", aiExtract: true }),
        n("gearbox_lube_return", "Gearbox Lube Return", { unit: "°F", aiExtract: true }),
        n("combustion_air_inlet", "Combustion Air Inlet", { unit: "°F", aiExtract: true }),
        n("skid_enclosure", "Skid Enclosure", { unit: "°F", aiExtract: true }),
        n("water_level", "Water Level", { aiExtract: true }),
        n("steam_flow", "Steam Flow", { unit: "lbs/hr", aiExtract: true }),
        n("feed_water_flow", "Feed Water Flow", { aiExtract: true }),
        n("condenser_steam_flow", "Condenser Steam Flow", { aiExtract: true }),
        n("natural_gas_temperature", "Natural Gas Temperature", { unit: "°F", aiExtract: true }),
        n("vibration_generator_nde", "Generator Non-Drive End Vibration", { unit: "in/sec", aiExtract: true }),
        n("vibration_gearbox", "Gearbox Vibration", { unit: "in/sec", aiExtract: true }),
        n("vibration_turbine_case", "Turbine Case Vibration", { unit: "mils", aiExtract: true }),
        n("status_monitor_comp_fuel_flow", "Status Monitor Comp. Fuel Flow", { aiExtract: true }),
        n("ops_kilowatts", "Kilowatts", { aiExtract: true }),
        n("varx_kilovars", "Kilovars", { aiExtract: true }),
        n("st60_61_turbine_speed", "ST60/61 Turbine Speed", { unit: "RPM", aiExtract: true }),
        n("dcs_calculated_tit", "DCS Calculated TIT", { unit: "°F", aiExtract: true }),
        n("turbine_outlet_temperature", "Turbine Outlet Temperatures", { unit: "°F", aiExtract: true }),
        n("compressor_discharge", "Compressor Discharge", { unit: "PSI", aiExtract: true }),
        n("gas_pressure_natural", "Gas Pressure Natural", { unit: "PSI", aiExtract: true }),
      ]),
      section("front-panel", "Front Panel", [
        n("front_calculated_tit", "Calculated TIT", { unit: "°F" }),
        n("front_starts", "Starts"),
        n("front_hour_meter", "Hour Meter"),
        { key: "gas_detection_ch1", label: "Gas Detection CH1 % LEL", type: "select", options: [{ label: "OK", value: "OK" }, { label: "Alarm", value: "Alarm" }] },
        { key: "gas_detection_ch2", label: "Gas Detection CH2 % LEL", type: "select", options: [{ label: "OK", value: "OK" }, { label: "Alarm", value: "Alarm" }] },
      ]),
      section("middle-panel", "Middle Panel", [
        n("middle_kilovars", "Kilovars"),
        n("middle_kilowatts", "Kilowatts"),
        n("generator_volts_ab", "Generator Volts A & B"),
        n("generator_volts_bc", "Generator Volts B & C"),
        n("generator_volts_ca", "Generator Volts C & A"),
        n("generator_amps_a", "Generator Amps A Phase"),
        n("generator_amps_b", "Generator Amps B Phase"),
        n("generator_amps_c", "Generator Amps C Phase"),
        n("generator_frequency", "Generator Frequency", { unit: "Hz" }),
      ]),
      section("generator-skid", "Generator Skid", [
        n("gas_fuel_supply_pressure", "Gas Fuel Supply Pressure"),
        n("gas_fuel_manifold_pressure", "Gas Fuel Manifold Pressure"),
        n("gas_fuel_inlet_pressure", "Gas Fuel Inlet Pressure"),
        n("turbine_lube_supply_pressure", "Turbine Lube Supply Pressure"),
        n("gearbox_pump_discharge_pressure", "Gearbox Pump Discharge Pressure"),
        n("gearbox_lube_oil_supply_pressure", "Gearbox Lube Oil Supply Pressure"),
        n("combustion_air_inlet_delta_p", "Combustion Air Inlet Delta P", { unit: "H2O" }),
        n("lube_oil_filter_delta_p", "Lube Oil Filter Delta P", { unit: "PSIP" }),
        n("generator_bearing_lube_supply", "Generator Bearing Lube Supply", { unit: "PSI" }),
        n("lube_oil_tank_level", "Lube Oil Tank Level", { unit: "%" }),
        n("turbine_lube_inlet_pressure", "Turbine Lube Inlet Pressure", { unit: "PSI" }),
      ]),
      section("optional", "Additional / Infrequent Readings", [
        n("relative_humidity", "Relative Humidity", { unit: "%", optional: true, infrequent: true }),
        n("temperature_monitor_f5", "Temperature Monitor - F5", { optional: true, infrequent: true }),
        t("control_mode", "Control Mode", { optional: true, infrequent: true }),
        n("status_monitor_f1_raw_fuel_flow", "Status Monitor F1 Raw Fuel Flow", { optional: true, infrequent: true }),
        n("vibration_monitor_f6_v", "Vibration Monitor F6 V", { optional: true, infrequent: true }),
        n("h20_injector", "H20 Injector", { optional: true, infrequent: true }),
        n("start_motor_cooling_oil_pressure", "Start Motor Cooling Oil Pressure", { optional: true, infrequent: true }),
        n("front_turbine_speed", "Front Panel Turbine Speed", { unit: "RPM", optional: true, infrequent: true }),
        n("boiler1_steam_flow", "Boiler 1 Steam Flow", { optional: true, infrequent: true }),
        n("boiler3_steam_flow", "Boiler 3 Steam Flow", { optional: true, infrequent: true }),
        n("boiler4_steam_flow", "Boiler 4 Steam Flow", { optional: true, infrequent: true }),
      ], "These readings are normally skipped. Fill them only when needed."),
    ],
  },
];

export const FORM_MAP = new Map(FORMS.map((form) => [form.key, form]));

export function getForm(formKey: string) {
  return FORM_MAP.get(formKey);
}

export function allFields(form: FormDefinition) {
  return form.sections.flatMap((section) => section.fields);
}
